sudo: required
dist: trusty
language: ruby
rvm:
  - 2.3.1
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tor
  - gem install bundler -v 1.14.6
  - gem install sigar -- --with-cppflags="-fgnu89-inline"
